### ISSUE TITLE
[improvement] Create an update helper.

### ISSUE THREAD

**Issue by rafaell-lycan** [tadeuzagallo/GithubPulse#23]
When a new version is released, alert the user about it.

(We can use Node.js for do that, or Pusher (free mode) )

Porcorntime use it.

**Comment by tadeuzagallo** [comment]
@txgruppi was supposed to implement that...

We were thinking just to check https://api.github.com/repos/tadeuzagallo/GithubPulse/tags for new releases...

**Comment by txgruppi** [comment]
I can work on it only on Monday.

**Comment by rafaell-lycan** [comment]
@txgruppi if I can help you with something, tell me =)

**Comment by GiaoGiaoCat** [comment]
Agree with @tadeuzagallo

**Comment by tadeuzagallo** [comment]
Hey everybody, I implemented a hackish version updater that fetches Github directly.
I've tested it quite a lot, but would appreciate any feedback... In order to make things easier, I updated a compiled fake old version to the [experimental branch](https://github.com/tadeuzagallo/GithubPulse/tree/experimental/dist)

The expect behavior is: When you open the app there should be an :warning: besides the version, once you hover it, you should see a message to click for update, it should close and relaunch already on the new version.

The UI is about as good as the code, so if anybody wanna suggest any thing, that'd be appreciated as well! :smiley:

**Comment by txgruppi** [comment]
@tadeuzagallo you can't wait for any ideia do come true. hahuhuahuahuahua

I will test it.

**Comment by tadeuzagallo** [comment]
@txgruppi Sorry man, I'm kinda compulsively developing while waiting to move.... Hehehe

**Comment by tadeuzagallo** [comment]
Well... Since everything seems to work I merged it on master and released it on [v0.3.3](https://github.com/tadeuzagallo/GithubPulse/releases/tag/v0.3.3)

/cc @ljharb

**Comment by rafaell-lycan** [comment]
Dafuck 3.3? o.O

**Comment by tadeuzagallo** [comment]
https://github.com/tadeuzagallo/GithubPulse/tags
