### ISSUE TITLE
Font looks ugly on Chrome for Mac, on external display

### ISSUE THREAD

**Issue by ngocphamm** [tadeuzagallo/GithubPulse#27]
I don't know why but it looks super ugly (to me) on Chrome Canary on Mac, on an external display. It's fine on the retina display, though.

Mac: 10.10.1
Canary: 42.0.2285.0

![screen shot 2015-01-23 at 1 12 43 pm](https://cloud.githubusercontent.com/assets/395123/5879950/e7d9a66c-a301-11e4-9db8-c6fa8ae5d864.png)

**Comment by caarlos0** [comment]
pretty normal here...

![screen shot 2015-01-25 at 11 56 08 pm](https://cloud.githubusercontent.com/assets/245435/5894413/c2d5dba4-a4ed-11e4-9727-4168e42e7545.png)

**Comment by ngocphamm** [comment]
Was that on an external display?

**Comment by caarlos0** [comment]
Don't know.. I don't usually use an external display...

**Comment by ngocphamm** [comment]
As I reported it happens on an external display.

**Comment by ngocphamm** [comment]
Changed the title so it's clear.

**Comment by tadeuzagallo** [comment]
@ngocphamm Sorry, I hadn't answered because I don't have a rMBP, it's already been hard to track a bug on a previous issue...

If do want to help me fix that, you could inspect the popup of the extension, change the font to helvetica and tell me if it looks fine...

Everything other than the popup is rendering fine? Because the graph resolution seems to be wrong as well...

**Comment by ngocphamm** [comment]
Errr. I'm sorry. It seems that this happens to all extension popup. I have µBlock and ZenHub and they are also ugly, even though I think it's probably less, maybe because of the different fonts. So it's probably a problem with my setup, or just Chrome (Canary).

**Comment by ngocphamm** [comment]
Yes, here it is. A bug of Chromium: https://code.google.com/p/chromium/issues/detail?id=324748
