### ISSUE TITLE
Streak for users I'm following doesn't work past a year

### ISSUE THREAD

**Issue by ljharb** [tadeuzagallo/GithubPulse#41]
https://github.com/getify/ has 423 but shows up as 366, and https://github.com/jdalton has 573 but shows up as 365.

**Comment by ljharb** [comment]
Also, how do I refresh my followers list in the client? I followed somebody new and right clicked the menu but it's not showing them.

**Comment by tadeuzagallo** [comment]
Well, about the number of commits, it happens on your profile as well, if you have more than 365 commits, the problem is that github just shows the chart for the ongoing year, and I have no idea how we can get the older commits... If you have any insight let me know.

As about the refresh, there's no way right now, there are a few issues with the following page, most of then caused because I wanted to sort the people by the streak length, but I just thought about removing it and replacing by a search field...

**Comment by ljharb** [comment]
Are you scraping the chart, or is there an API? If scraping, the "current streak" (span.contrib-number) is the accurate number.

(I think both sorting and searching the user list would be good)

**Comment by tadeuzagallo** [comment]
I hadn't actually thought about that... haha
I'm scrapping just the chart (https://github.com/:username/contributions), but that could be a better ideia.
About the sort, the problem is that some people are following like 900 people, which means ~9 requests to get the list of users + 900 requests to get the streak per user.

**Comment by ljharb** [comment]
That seems problematic only for the initial pull - once you've got the list, then you know who the most important/likely people are to scrape frequently, which are the ones at the top of the list of non-zeroes sorted by streak length. The zeroes could be scraped much more rarely.

For the initial load, you could certainly stagger those 900 requests over a longer length of time, and provide a text box (for me to enter usernames I want scraped immediately) or a refresh button on a list of usernames (for me to trigger an immediate scrape) - it's a tiny bit clunkier, and you'd need a "loading streak" indicator which would stick around for awhile (but you'd want that regardless), but it would let me prioritize the few people I want to compete with :-)

**Comment by ljharb** [comment]
Any update on this?

**Comment by tadeuzagallo** [comment]
No, nothing yet :disappointed: 
I've been super busy, sorry, but I'll try to find some time to work on it... but if you wan't to take that on the mean time... you're more than welcome :)

**Comment by ljharb** [comment]
ping :-)

**Comment by tadeuzagallo** [comment]
Hey, a little bit late but... I tried to fix it on v0.3.9, let me know if you see any issues.

**Comment by ljharb** [comment]
I don't seem to be able to update past `v0.3.8`. I click the "restart and apply" button and it just keeps telling me I'm on that version. I was able to update from `v0.3.7` to `v0.3.8` tho.

**Comment by tadeuzagallo** [comment]
That's bad... I didn't change anything related to that though, maybe
something changed in El Capitan, I'll take a look.

**Comment by ljharb** [comment]
I'm still on Yosemite.

**Comment by tadeuzagallo** [comment]
The good news are that I think I've fixed it, the bad news are that I screwed up before :(
I think I've generate the app before bumping the version, so you might have already updated, plus the download code was broken, which means that everyone might get stuck in that state ( :( again).

Let me know how it goes for you.

**Comment by ljharb** [comment]
I was able to successfully update to `v0.3.10` - this appears to fix my issue, thanks!

update: i actually had to delete and reinstall the one that was stuck on v0.3.8 :-(
